### ISSUE TITLE
currency is not supported. Please update the template.

### ISSUE THREAD

**Issue by eugenpotlog** [gtm-templates-knowit-experience/ga-eec-to-ga4-ecom-converter#2]
Please update the template so it also converts the currency from GA4 ecommerce object into the EEC ecommerce object. I've done this locally. You can find the file with my updates here: https://drive.google.com/file/d/1_5zRL6w89WoRPCSWqYirT0-hYMFORy5B/view?usp=sharing

**Comment by EivindSavio** [comment]
Commented on wrong template. Currency is updated in the other template.
